[mcp_servers.awsdocs]
url = "https://knowledge-mcp.global.api.aws"
enabled = true

[mcp_servers.aws-mcp]
command = "uvx"
args = [
  "mcp-proxy-for-aws@latest",
  "https://aws-mcp.us-east-1.api.aws/mcp",
  "--metadata",
  "AWS_REGION=us-west-2"
]
enabled = false
